repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile=black]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        name: black (python)
        with:
          options: "--exclude ./src/auth/ifrastructure/db/migrations/versions/"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy
        name: mypy (python)
        args: [--config-file=mypy.ini, --explicit-package-bases, --exclude=src/auth/infrastructure/db/migrations/versions/, .]
        additional_dependencies: [pytest==8.3.4]
        pass_filenames: false