"""auto_20250423_101906

Revision ID: 12fd64a1a519
Revises: de5519ff4f07
Create Date: 2025-04-23 10:19:08.566363

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12fd64a1a519"
down_revision: Union[str, None] = "de5519ff4f07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column("permissions", sa.ARRAY(sa.String(length=50)), nullable=False),
    )
    op.add_column(
        "users", sa.Column("user_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=255), nullable=False)
    )
    op.add_column("users", sa.Column("password", sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, "users", ["user_name"])
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password_hash", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "password")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "user_name")
    op.drop_column("roles", "permissions")
    # ### end Alembic commands ###
