name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Isort  
        uses: isort/isort-action@v1
        with:
          configuration: "--check-only --diff --profile=black"

      - name: Run black
        uses: psf/black@stable
        with:
          options: "--exclude src/auth/ifrastructure/alembic/versions/"

      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'
       
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create .env file      
        run: |
          echo "${{ secrets.env }}" >> .env

      - name: Docker up
        run: |
          docker compose up -d

      - name: Run migrations
        run: |
          docker compose exec auth poetry run src/alembic -c src/auth/main/alembic.ini upgrade head
        env:
          DATABASE_URL: ${{ secrets.env.TEST_DATABASE_URL }}    
          
      - name: Run tests with pytest
        run: |
          docker compose exec auth poetry run pytest src/ --cov --cov-report=xml
  
      - name: Install diff-cover
        run: |
          pip install diff-cover    
  
      - name: Run diff-cover
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            diff-cover coverage.xml --compare-branch=origin/${{ github.base_ref }}
          else
            diff-cover coverage.xml --compare-branch=origin/main
          fi