name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Isort  
        uses: isort/isort-action@v1
        with:
          configuration: "--check-only --diff --profile=black"

      - name: Run black
        uses: psf/black@stable
        with:
          options: "--exclude src/auth/ifrastructure/alembic/versions/"

      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'
       
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Create .env file      
      run: |
          echo "${{ secrets.env }}" >> .env

    - name: Docker_start
      run: |
        docker compose up -d

    - name: Run tests
      run: |
        docker compose exec auth poetry run pytest src/tests -v --cov=src --cov-report=xml -s
      env:
        DATABASE_URL: ${{secrets.env.TEST_DB_URL}}
